name: vini_drive_ops
description: A driver and admin management app with Flutter frontend and Google Apps Script backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  provider: ^6.1.1
  url_launcher: ^6.2.4
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.65.0
  pdf: ^3.10.7
  permission_handler: ^11.2.0
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0
  freezed: ^2.4.6
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
   