name: vini_drive_ops
description: A driver and admin management app with Flutter frontend and Google Apps Script backend.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  shared_preferences: ^2.2.3
  image_picker: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.1
  url_launcher: ^6.3.0
  file_picker: ^6.1.1
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.65.0
  pdf: ^3.10.7
  permission_handler: ^11.3.1
  path: ^1.8.3
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/