name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2.10.0
      with:
        flutter-version: '3.10.0'
        channel: 'stable'
        cache: true

    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.android/build-cache
          **/.dart_tool
          **/.flutter-plugins
          **/.flutter-plugins-dependencies
          **/.packages
          build
        key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock', '**/pubspec.yaml', '**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          flutter-${{ runner.os }}-
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze
    
    - name: Run tests
      run: flutter test
    
    - name: Build APK
      run: |
        flutter clean
        flutter build apk --release --split-per-abi --target-platform android-arm,android-arm64,android-x64 --obfuscate --split-debug-info=build/debug-info
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apks
        path: |
          build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          build/app/outputs/flutter-apk/app-x86_64-release.apk
        retention-days: 7
        if-no-files-found: error