name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLUTTER_VERSION: '3.22.0'
  JAVA_VERSION: '11'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Cache Pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.PUB_CACHE }}
            ${{ runner.tool_cache }}/flutter
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: |
          flutter pub get
        continue-on-error: false

      - name: Verify Dart SDK constraints
        run: |
          DART_SDK_CONSTRAINT=$(grep 'sdk:' pubspec.yaml | sed 's/sdk://;s/^[[:space:]]*//;s/[[:space:]]*$//')
          if [ -z "$DART_SDK_CONSTRAINT" ]; then
            echo "Error: Missing SDK constraint in pubspec.yaml"
            echo "Please add:"
            echo "environment:"
            echo "  sdk: '^3.4.0'"
            exit 1
          fi
        continue-on-error: false

      - name: Analyze project
        run: flutter analyze
        continue-on-error: true

      - name: Run tests
        run: flutter test --coverage
        continue-on-error: true

      - name: Build Android APK
        run: flutter build apk --release --verbose
        continue-on-error: false

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            coverage/
            test/reports/
          retention-days: 7

      - name: Check build status
        if: failure()
        run: |
          echo "Build failed. Please check the logs above for more details."
          echo "Common issues:"
          echo "1. Missing or incorrect SDK constraints in pubspec.yaml"
          echo "2. Incompatible package versions"
          echo "3. Failed tests or analysis issues"
          exit 1