name: Flutter CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'android/**'
      - 'ios/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'
      - 'android/**'
      - 'ios/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: '3.19.3'
  JAVA_VERSION: '17'
  DART_SDK_VERSION: '>=3.4.0 <4.0.0'
  GRADLE_VERSION: '7.6'
  ANDROID_SDK_VERSION: '33'

jobs:
  validate-setup:
    name: Validate Project Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify pubspec.yaml
        id: verify-pubspec
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            echo "::error::pubspec.yaml not found"
            exit 1
          fi
          
          # Check SDK constraints
          SDK_CONSTRAINT=$(grep -A 1 'environment:' pubspec.yaml | grep 'sdk:' || echo '')
          if [ -z "$SDK_CONSTRAINT" ]; then
            echo "Adding Dart SDK constraint to pubspec.yaml"
            awk '/name:/{print;print "\nenvironment:\n  sdk: \"'"$DART_SDK_VERSION"'\"\n";next}1' pubspec.yaml > pubspec.yaml.tmp
            mv pubspec.yaml.tmp pubspec.yaml
          fi
        shell: bash

  code-quality:
    name: Code Quality Checks
    needs: validate-setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Cache Pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.tool_cache }}/flutter
            ~/.pub-cache
            ~/AppData/Local/Pub/Cache
            ~/Library/Caches/Pub
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Check code formatting
        run: |
          echo "Checking code formatting..."
          dart format --output=none --set-exit-if-changed .

      - name: Analyze project
        run: |
          echo "Running Flutter analyze..."
          flutter analyze

  build-and-test:
    name: Build and Test
    needs: code-quality
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        build-type: [apk, appbundle]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'
          cache-dependency-path: "**/build.gradle*"

      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ env.FLUTTER_VERSION }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Cache Pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.tool_cache }}/flutter
            ~/.pub-cache
            ~/AppData/Local/Pub/Cache
            ~/Library/Caches/Pub
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml', '**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: |
          echo "Installing Flutter dependencies..."
          flutter clean
          flutter pub get
          echo "Dependencies installed successfully"

      - name: Setup Android signing
        if: github.event_name != 'pull_request'
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'keystore.jks'
          fileDir: './android/app/'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Create key.properties
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Run tests
        run: |
          mkdir -p test/reports
          flutter test --coverage --machine > test-report.json || true
          flutter test --coverage --test-randomize-ordering-seed random

      - name: Build Android ${{ matrix.build-type }}
        run: |
          if [ "${{ matrix.build-type }}" = "apk" ]; then
            echo "Building release APK..."
            flutter build apk --release
          else
            echo "Building App Bundle..."
            flutter build appbundle --release
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: release-${{ matrix.build-type }}
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          retention-days: 14

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.build-type }}
          path: |
            coverage/
            test/reports/
            test-report.json
          retention-days: 14

      - name: Build status summary
        if: always()
        run: |
          echo "Build Status Summary for ${{ matrix.build-type }}:"
          echo "-------------------"
          echo "✓ Project setup validation"
          echo "✓ Code quality checks"
          echo "✓ Dependencies installation"
          if [ -f "coverage/lcov.info" ]; then
            echo "✓ Tests executed (results in artifacts)"
          else
            echo "❌ Tests failed"
            exit 1
          fi
          if [ "${{ matrix.build-type }}" = "apk" ]; then
            if [ -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
              echo "✓ APK build successful"
            else
              echo "❌ APK build failed"
              exit 1
            fi
          else
            if [ -f "build/app/outputs/bundle/release/app-release.aab" ]; then
              echo "✓ App Bundle build successful"
            else
              echo "❌ App Bundle build failed"
              exit 1
            fi
          fi